### ISSUE TITLE
setServerUrl with HTTP host throws class cast exception on URL openConnection

### ISSUE THREAD

**Issue by porto88** [amplitude/Amplitude-Java#83]
Java SDK Version 1.10.1

## Expected Behavior
No error when setting non-https serverUrl

## Current Behavior
When setting a non-https serverUrl the following exception is thrown due to an explicit cast in the code at line 42 in class
com.amplitude.HttpCall

connection = (HttpsURLConnection) new URL(apiUrl).openConnection(proxy);

Flush Thread Error: java.util.concurrent.ExecutionException: java.lang.ClassCastException: class sun.net.www.protocol.http.HttpURLConnection cannot be cast to class javax.net.ssl.HttpsURLConnection (sun.net.www.protocol.http.HttpURLConnection and javax.net.ssl.HttpsURLConnection are in module java.base of loader 'bootstrap')
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.amplitude.HttpTransport$SendEventsTask.run(HttpTransport.java:419)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: class sun.net.www.protocol.http.HttpURLConnection cannot be cast to class javax.net.ssl.HttpsURLConnection (sun.net.www.protocol.http.HttpURLConnection and javax.net.ssl.HttpsURLConnection are in module java.base of loader 'bootstrap')
	at com.amplitude.HttpCall.makeRequest(HttpCall.java:42)
	at com.amplitude.HttpTransport.lambda$sendEvents$0(HttpTransport.java:114)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

## Possible Solution
Cast conditionally based on serverUrl or cast to java.net.HttpURLConnection

## Steps to Reproduce
 

1.  Amplitude amplitudeWebClient = Amplitude.getInstance("Web Client");
2.  amplitudeWebClient.setServerUrl("http://localhost:8080/batch");
3. amplitudeWebClient.init("key");
4. amplitudeWebClient.logEvent(new Event("testType","userId"));
5. amplitudeWebClient.flushEvents();

## Environment
Java 11

**Comment by yuhao900914** [comment]
Hi @porto88,
In Java SDK, we are using HttpsURLConnection which is required to use a https server URL. This is working as expected. 
Any reason you want to use the localhost server URL? Is that only for the test purpose? 

Thanks.

**Comment by porto88** [comment]
Yes, for testing purposes. The setServerUrl() seems to support both http and https.

**Comment by yuhao900914** [comment]
@porto88 
Since we currently have a high volume of tickets and this doesn't have a high priority. I would recommend using some free https services as a workaround for testing. like [webhook.site](https://webhook.site/). 
Thanks.

**Comment by yuhao900914** [comment]
Closing this Github issue since it works as expected.
